const configs=[{name:'订单关闭原因',code:'order_close_reason',system:'订单系统',fieldCount:3,desc:'销售订单关闭时供操作人选择关闭原因',refs:'销售订单、订单审核',count:6},{name:'客户等级',code:'customer_level',system:'客户系统',fieldCount:5,desc:'企业客户分层与价格策略引用',refs:'客户档案、价格策略',count:4},{name:'付款方式',code:'payment_method',system:'财务系统',fieldCount:4,desc:'订单与合同可选付款方式',refs:'销售订单、采购合同',count:5},{name:'商品单位',code:'product_unit',system:'商品系统',fieldCount:4,desc:'商品和报价的标准计量单位',refs:'商品档案、报价单',count:12},{name:'发票类型',code:'invoice_type',system:'财务系统',fieldCount:6,desc:'客户开票申请可选类型',refs:'发票管理',count:3}];
let fields=[{name:'原因编码',code:'reason_code',type:'文本',required:true,default:'—',desc:'业务唯一编码'},{name:'原因名称',code:'reason_name',type:'文本',required:true,default:'—',desc:'面向操作人显示'},{name:'允许重新下单',code:'allow_reorder',type:'布尔',required:true,default:'否',desc:'关闭后是否可复制订单'}];
let values=[{reason_code:'BUYER_CANCEL',reason_name:'买家主动取消',allow_reorder:'是',status:'启用',sort:10},{reason_code:'PRICE_CHANGED',reason_name:'价格发生变化',allow_reorder:'是',status:'启用',sort:20},{reason_code:'OUT_OF_STOCK',reason_name:'商品库存不足',allow_reorder:'是',status:'启用',sort:30},{reason_code:'CREDIT_REJECTED',reason_name:'信用审核未通过',allow_reorder:'否',status:'启用',sort:40},{reason_code:'DUPLICATE_ORDER',reason_name:'重复下单',allow_reorder:'否',status:'启用',sort:50},{reason_code:'OTHER',reason_name:'其他原因',allow_reorder:'否',status:'停用',sort:99}];
let current=0,valueFilter='all',systemFilter='全部',fieldType='文本';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('is-show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').classList.remove('is-show'),1700)}
function renderConfigs(){const q=$('#configSearch').value.trim().toLowerCase();const rows=configs.map((c,i)=>({c,i})).filter(x=>(systemFilter==='全部'||x.c.system===systemFilter)&&(!q||`${x.c.name}${x.c.code}`.toLowerCase().includes(q)));$('#configTotal').textContent=rows.length;$('#configRows').innerHTML=rows.map(({c,i})=>`<tr><td><div class="c-config-name"><span class="c-config-name__icon">${c.name[0]}</span><button class="c-config-entry" data-config="${i}">${c.name}</button></div></td><td><code>${c.code}</code></td><td>${c.system}</td><td><b>${c.fieldCount}</b> 个</td><td>${c.count} 条</td><td>${c.refs}</td><td><span class="tag tag--success">已启用</span></td><td>今天 10:24</td><td><button class="c-action-link c-config-entry" data-config="${i}">进入配置 →</button></td></tr>`).join('')||'<tr><td colspan="9">暂无匹配配置</td></tr>';$$('[data-config]').forEach(b=>b.onclick=()=>selectConfig(+b.dataset.config))}
function selectConfig(i){current=i;const c=configs[i];$('#detailName').textContent=c.name;$('#detailCode').textContent=c.code;$('#detailDesc').textContent=c.desc;$('#detailRefs').textContent=c.refs;$('#homeView').classList.remove('is-active');$('#detailView').classList.add('is-active');positionAnnotations()}
function renderValues(){const q=$('#valueSearch').value.trim().toLowerCase();const rows=values.map((v,i)=>({v,i})).filter(({v})=>(valueFilter==='all'||v.status===valueFilter)&&(!q||Object.values(v).join(' ').toLowerCase().includes(q)));$('#valueCount').textContent=values.length;$('#valueHead').innerHTML=`<tr>${fields.map(f=>`<th>${f.name}<br><code>${f.code}</code></th>`).join('')}<th>排序</th><th>操作</th></tr>`;$('#valueRows').innerHTML=rows.map(({v,i})=>`<tr>${fields.map(f=>`<td>${v[f.code]??'—'}</td>`).join('')}<td>${v.sort}</td><td><div class="c-actions"><button class="c-action-link" data-edit-value="${i}">编辑</button><button class="c-action-link" data-toggle-value="${i}">${v.status==='启用'?'停用':'启用'}</button><button class="c-action-link c-action-link--danger" data-delete-value="${i}">删除</button></div></td></tr>`).join('')||`<tr><td colspan="${fields.length+2}">暂无匹配数据</td></tr>`;$$('[data-toggle-value]').forEach(b=>b.onclick=()=>toggleValue(+b.dataset.toggleValue));$$('[data-delete-value]').forEach(b=>b.onclick=()=>deleteValue(+b.dataset.deleteValue));updateJson()}
function addLog(text){$('#logList').insertAdjacentHTML('afterbegin',`<p><b>林晓</b> ${text}<small>刚刚</small></p>`)}
function toggleValue(i){const v=values[i];v.status=v.status==='启用'?'停用':'启用';addLog(`${v.status}配置值“${v.reason_name||v[fields[0].code]}”`);renderValues();toast(`配置值已${v.status}`)}
function deleteValue(i){const v=values[i];values.splice(i,1);addLog(`删除配置值“${v.reason_name||v[fields[0].code]}”`);renderValues();toast('配置值已删除，操作已记录日志')}
function renderFields(){ $('#fieldCount').textContent=fields.length;$('#fieldRows').innerHTML=fields.map((f,i)=>`<tr><td>${f.name}</td><td><code>${f.code}</code></td><td>${f.type}</td><td>${f.required?'是':'否'}</td><td>${f.default}</td><td>${f.desc}</td><td><div class="c-actions"><button class="c-action-link">编辑</button><button class="c-action-link" data-del-field="${i}">删除</button></div></td></tr>`).join('');$$('[data-del-field]').forEach(b=>b.onclick=()=>toast('字段已被配置数据引用，不能直接删除'))}
function updateJson(){const data=values.filter(v=>v.status==='启用').slice(0,2).map(v=>Object.fromEntries(fields.map(f=>[f.code,v[f.code]])));$('#jsonPreview').textContent=JSON.stringify({configCode:configs[current].code,data},null,2)}
function openDrawer(id){$('#mask').classList.add('is-open');$(id).classList.add('is-open')}function closeDrawers(){$('#mask').classList.remove('is-open');$$('.c-drawer').forEach(x=>x.classList.remove('is-open'))}
function buildValueForm(){ $('#valueForm').innerHTML=fields.map(f=>`<label>${f.name} ${f.required?'<em>*</em>':''}<input class="input" data-value-code="${f.code}" placeholder="请输入${f.name}"><small>字段编码：${f.code}</small></label>`).join('')+`<label>排序<input class="input" data-value-code="sort" value="${(values.length+1)*10}"></label>`}
renderConfigs();renderFields();renderValues();
$('#configSearch').oninput=renderConfigs;$$('[data-system]').forEach(b=>b.onclick=()=>{systemFilter=b.dataset.system;$$('[data-system]').forEach(x=>x.classList.toggle('is-selected',x===b));renderConfigs()});$('#backHomeBtn').onclick=()=>{$('#detailView').classList.remove('is-active');$('#homeView').classList.add('is-active');positionAnnotations()};$('#valueSearch').oninput=renderValues;$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('is-selected',x===b));$$('[data-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.panel===b.dataset.tab));positionAnnotations()});$$('[data-filter]').forEach(b=>b.onclick=()=>{valueFilter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('is-selected',x===b));renderValues()});
$('#newConfigBtn').onclick=()=>openDrawer('#configDrawer');$('#addFieldBtn').onclick=()=>openDrawer('#fieldDrawer');$('#addValueBtn').onclick=()=>{buildValueForm();openDrawer('#valueDrawer')};$$('[data-close]').forEach(x=>x.onclick=closeDrawers);$('#mask').onclick=closeDrawers;
$('#saveConfigBtn').onclick=()=>{const name=$('#newConfigName').value.trim(),code=$('#newConfigCode').value.trim();if(!name||!/^[a-z][a-z0-9_]*$/.test(code)){toast('请填写名称和正确的配置编码');return}configs.push({name,code,system:'订单系统',fieldCount:0,desc:$('#newConfigDesc').value||'暂无说明',refs:'尚未调用',count:0});current=configs.length-1;closeDrawers();renderConfigs();selectConfig(current);toast('配置项已创建，请继续定义多个字段')};
$$('[data-type]').forEach(b=>b.onclick=()=>{fieldType=b.dataset.type;$$('[data-type]').forEach(x=>x.classList.toggle('is-selected',x===b))});$('#requiredSwitch').onclick=()=>$('#requiredSwitch').classList.toggle('is-on');$('#saveFieldBtn').onclick=()=>{const name=$('#newFieldName').value.trim(),code=$('#newFieldCode').value.trim();if(!name||!/^[a-z][a-z0-9_]*$/.test(code)){toast('请填写字段名称和正确的字段编码');return}if(fields.some(f=>f.code===code)){toast('字段编码已存在');return}fields.push({name,code,type:fieldType,required:$('#requiredSwitch').classList.contains('is-on'),default:'—',desc:$('#newFieldDesc').value||'—'});values.forEach(v=>v[code]='—');closeDrawers();renderFields();renderValues();toast('字段已新增，返回结构已同步更新')};
$('#saveValueBtn').onclick=()=>{const item={status:'启用'};let ok=true;$$('[data-value-code]').forEach(x=>{if(!x.value.trim()&&x.dataset.valueCode!=='sort')ok=false;item[x.dataset.valueCode]=x.dataset.valueCode==='sort'?Number(x.value):x.value.trim()});if(!ok){toast('请填写所有必填字段');return}values.push(item);closeDrawers();renderValues();toast('配置数据已保存，可供业务模块读取')};
$('#copyBtn').onclick=()=>{navigator.clipboard?.writeText($('#jsonPreview').textContent);toast('JSON 已复制')};

const anns=[{id:1,type:'页面',title:'公共配置入口',text:'首页只展示各系统下的配置项，业务模块通过配置编码读取。'},{id:2,type:'交互',title:'配置项列表',text:'按配置名称、编码和所属系统查询；点击后进入独立配置详情。'},{id:3,type:'页面',title:'配置详情',text:'详情不展示配置级状态，围绕当前配置维护数据、字段、调用说明和变更记录。'},{id:4,type:'规则',title:'三层数据模型',text:'配置项定义字典，字段定义返回结构，配置数据维护每个字段的具体值。'},{id:5,type:'字段',title:'配置数据',text:'每行是一条字典数据；操作栏直接提供编辑、启用或停用、删除，删除后写入日志。'},{id:6,type:'字段',title:'多字段定义',text:'一个配置项可定义多个字段；字段名称、编码、类型、必填和说明均可独立维护。'},{id:7,type:'交互',title:'业务调用',text:'提供按 configCode 获取启用数据的调用约定，并展示实际 JSON 返回结构。'},{id:8,type:'交互',title:'原型标注模式',text:'关闭后编号点与抽屉同时隐藏，页面状态与业务交互保持不变。'},{id:9,type:'待确认',title:'配置缓存策略',text:'待确认业务模块实时读取还是缓存配置；影响变更生效时间与缓存刷新方式。',target:'detailCode'}];const colors={页面:'#1677ff',字段:'#722ed1',交互:'#13a8a8',规则:'#fa8c16',待确认:'#eb2f96'};let annFilter='全部';
function target(a){return a.target?$('#'+a.target):$(`[data-annotation="${a.id}"]`)}function renderAnnotations(){const ts=['全部','页面','字段','交互','规则','待确认'];$('#annotationFilters').innerHTML=ts.map(t=>`<button class="c-annotation-filter ${annFilter===t?'is-selected':''}" data-ann-filter="${t}">${t} ${t==='全部'?anns.length:anns.filter(a=>a.type===t).length}</button>`).join('');$('#annotationList').innerHTML=anns.filter(a=>annFilter==='全部'||a.type===annFilter).map(a=>`<article class="c-annotation-item" data-ann="${a.id}" style="--ann-color:${colors[a.type]}"><div class="c-annotation-item__head"><span class="c-annotation-num">${a.id}</span><b>${a.title}</b><span class="c-annotation-type">${a.type}</span></div><p>${a.text}</p></article>`).join('');$$('[data-ann-filter]').forEach(b=>b.onclick=()=>{annFilter=b.dataset.annFilter;renderAnnotations()});$$('[data-ann]').forEach(x=>x.onclick=()=>focusAnn(+x.dataset.ann));positionAnnotations()}
function positionAnnotations(){$$('.c-annotation-dot').forEach(x=>x.remove());if(document.body.classList.contains('annotations-off'))return;anns.forEach(a=>{const t=target(a);if(!t||!t.offsetParent)return;const r=t.getBoundingClientRect(),d=document.createElement('button');d.className='c-annotation-dot';d.textContent=a.id;d.style.cssText=`--ann-color:${colors[a.type]};left:${r.left+6}px;top:${r.top+6}px`;d.onclick=()=>focusAnn(a.id);document.body.appendChild(d)})}function focusAnn(id){const a=anns.find(x=>x.id===id),t=target(a);t?.scrollIntoView({behavior:'smooth',block:'center'});t?.classList.add('is-highlighted');setTimeout(()=>t?.classList.remove('is-highlighted'),1500);$(`[data-ann="${id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}
function toggleAnnotations(){const off=document.body.classList.toggle('annotations-off');$('#annotationToggle').textContent=off?'开启标注':'关闭标注';positionAnnotations()}$('#closeAnnotations').onclick=toggleAnnotations;$('#annotationToggle').onclick=toggleAnnotations;window.addEventListener('resize',positionAnnotations);renderAnnotations();setTimeout(positionAnnotations,50);
